version: 2.1

commands:
  build:
    steps:
      - checkout

      - run:
          command: npm version

      - run:
          command: npm ci

      - run:
          command: npm run lint

      - run:
          command: npm run type-check

      - run:
          name: Install mediainfo
          command: |
            apt-get update
            wget https://mediaarea.net/download/binary/libzen0/0.4.37/libzen0_0.4.37-1_amd64.Debian_8.0.deb
            dpkg -i libzen0_0.4.37-1_amd64.Debian_8.0.deb
            wget https://mediaarea.net/download/binary/libmediainfo0/18.08.1/libmediainfo0_18.08.1-1_amd64.Debian_8.0.deb
            apt install libmms0
            dpkg -i libmediainfo0_18.08.1-1_amd64.Debian_8.0.deb
            wget https://mediaarea.net/download/binary/mediainfo/18.08.1/mediainfo_18.08.1-1_amd64.Debian_8.0.deb
            dpkg -i mediainfo_18.08.1-1_amd64.Debian_8.0.deb

      - run:
          command: npm run test -- --ci --coverage --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/results.xml"

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit

jobs:

  test-v10:
    docker:
      - image: node:10
    steps:
      - build

  test-v12:
    docker:
      - image: node:12
    steps:
      - build

  publish-v10:
    docker:
      - image: node:10
    steps:
      - build
      - publish

workflows:
  test-deploy:
    jobs:
      - test-v10
      - test-v12
